# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db3ecafdfaff9e072e51c4b02931e3e3353f65ab55f34706dd94e810e4b44f0fee57f566017bf829d6b0cd3fe3a5f778cac363d9fdddf291831674a8c2fd34a

test:
  secret_key_base: cd426d5e77999e287e2bfeded3daa05e5e23d580dba188aaedd224d17d6d673e8b76ca5b8c4bf15b030c71618a536e289e9d3aecd1f57bcae782e40b52f0a3b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
